spring:
  main:
    show-banner: true
  thymeleaf:
    cache: true
  freemarker:
    cache: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring_boot?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 199011081108
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8443
  #  ssl:
  #    key-store: file:///path/to/mykeys.jks
  #    key-store-password: letmein
  #    key-password: letmein
logging:
  level:
    root: WARN
    org.springframework.security: DEBUG


