spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring_boot?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 199011081108
    driver-class-name: com.mysql.jdbc.Driver