spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring_boot?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 199011081108
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    tomcat:
      max-wait: 60000
      initial-size: 5
      min-idle: 5
      max-active: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      connection-properties:
        druid:
          stat:
            merge-sql: true;
            slow-sql-millis: 5000
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false

  freemarker:
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
  thymeleaf:
    cache: false
#  热部署，关闭
  devtools:
    restart:
      enabled: false
      trigger-file: ./templates
# profile 激活选择
  profiles:
    active: dev
#
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

mybatis:
  mapperLocations: classpath*:com/rayeston/mybatis/*.xml

#  security
security:
  user:
    password: 123456
    name: ray
# 日志级别
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    logging.level.org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    logging.level.com.itmuch: DEBUG


#  配置spring-cloud
server:
  port: 1111
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:${server.port}/eureka/
# 自定义全局值
name: lee
id: ${random.uuid}
my:
  servers:
    - 634178463@qq.com
    - yi@rayest.cn





